### ISSUE TITLE
Other ways to use roles in playbooks not supported

### ISSUE THREAD

**Issue by rndmh3ro** [volanja/ansible_spec#29]
Ansible allows multiple ways to define roles in playbooks (see [here](http://docs.ansible.com/playbooks_roles.html#roles)):

Right now, only this way is supported by ansible_spec:
```
- name: foo
  hosts: server_foo
  gather_facts: True
  roles:
  - foo_role
```
These two do not work:
```
- name: foo
  hosts: server_foo
  gather_facts: True
  roles:
  - roles: foo_role
```
```
- name: foo
  hosts: server_foo
  gather_facts: True
  roles:
  - { role: foo_app_instance, dir: '/opt/b',  port: 5001 }
```

Would ne nice if this could be supported!

**Comment by volanja** [comment]
I will support two ways.

**No1** Use role `nginx`, `mariadb`

```
- name: Ansible-Sample-TDD
  hosts: server
  user: root
  roles:
  - roles: nginx
  - roles: mariadb
```

**No2** Use role `common`, `nginx`, `mariadb`

```
- name: Ansible-Sample-TDD
  hosts: server
  user: root
  roles:
  - common
  - { role: nginx, dir: '/opt/a',  port: 5001 }
  - { role: mariadb, dir: '/opt/b',  port: 5002 }
```

**Comment by rndmh3ro** [comment]
First one should be:roles: - role: foo‎not roles.Otherwise this sounds great!                                                                                                                                                                                                                                                                                                                                                                                                                   Von: volanjaGesendet: Mittwoch, 8. Juli 2015 17:35An: volanja/ansible_specAntwort an: volanja/ansible_specCc: Sebastian GumprichBetreff: Re: [ansible_spec] Other ways to use roles in playbooks not supported (#29)I will support two ways.

No1 Use role nginx, mariadb

- name: Ansible-Sample-TDD
  hosts: server
  user: root
  roles:
  - roles: nginx
  - roles: mariadb


No2 Use role common, nginx, mariadb

- name: Ansible-Sample-TDD
  hosts: server
  user: root
  roles:
  - common
  - { role: nginx, dir: '/opt/a',  port: 5001 }
  - { role: mariadb, dir: '/opt/b',  port: 5002 }


—Reply to this email directly or view it on GitHub.

**Comment by volanja** [comment]
@rndmh3ro Thank you review it.

I replace from `roles` to `role`.

**No1 (new)** Use role nginx, mariadb
```
- name: Ansible-Sample-TDD
  hosts: server
  user: root
  roles:
  - role: nginx
  - role: mariadb
```
