### ISSUE TITLE
Testing playbooks with 3rd party roles and custom tasks

### ISSUE THREAD

**Issue by wilkko** [volanja/ansible_spec#52]
Is it possible to write and run tests that would test playbooks that have 3rd party roles and custom tasks? Assumption with ansible_spec seems to be that all the specs are within roles.

**Comment by conorsch** [comment]
> Assumption with ansible_spec seems to be that all the specs are within roles.

@wilkko I'm not the maintainer, but your assumption appears correct. If you're trying to test playbooks that require external roles, simply script fetching the external roles prior to running the tests. As long as the roles do not have files matching `spec/*_spec.rb`, then no Serverspec tests will be run for those roles. (That's good, because otherwise including the external roles would cause the tests to fail.)

**Comment by volanja** [comment]
I designed directory that spec are within roles.(e.g. roles/<role name>)/spec/*_spec.rb)
So, 3rd party roles and custom tasks is not run test.

But If you use `include` in ansible playbook, ansible_spec detect `include`.
I hope it will be helpful to you.

```
# site.yml (playbook)
- name: Ansible-Sample-TDD
  hosts: server
  user: root
  roles:
    - mariadb #<= test target (roles/mariadb/spec/*_spec.rb)
- include: nginx.yml
```

```
# nginx.yml (playbook)
- name: Ansible-Nginx
  hosts: web
  user: nginx
  roles:
    - nginx # <= test target (roles/nginx/spec/*_spec.rb)
```
