### ISSUE TITLE
host patterns/ranges don't work with dynamic inventories

### ISSUE THREAD

**Issue by temyers** [volanja/ansible_spec#64]
I'm using a dynamic inventory: ec2.py

`ec2.py --list` contains the following:

```
"tag_Name_server1": [
    "1.2.3.4"
  ], 
  "tag_Name_server2": [
    "1.2.3.5"
  ], 
```

My playbook contains:

```
 - name: servers
   hosts: tag_Name_server[1:2]
   roles:
    - server
```

`rake -T` includes:
```no hosts matched for tag_Name_server[1:2]
...
NoMethodError: undefined method`each' for "tag_Name_server[1:2]":String

```

expected:
* `rake serverspec:server` should run specs against serves ["1.2.3.4","1.2.3.5"]
actual:
* rake fails with the `NoMethodError` above
```
